# Generated by Django 4.2 on 2023-04-10 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openai', '0002_language_story_sentence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoryLine',
        ),
        migrations.AddField(
            model_name='story',
            name='story_level',
            field=models.CharField(choices=[('a1', 'A1'), ('a2', 'A2'), ('b1', 'B1'), ('b2', 'B2'), ('c1', 'C1'), ('c2', 'C2')], default='b1', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sentence',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story', to='openai.story'),
        ),
        migrations.AlterField(
            model_name='story',
            name='native_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='native_language', to='openai.language'),
        ),
        migrations.AlterField(
            model_name='story',
            name='target_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_language', to='openai.language'),
        ),
    ]
