# Generated by Django 4.2 on 2023-04-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai', '0006_alter_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
