# Generated by Django 4.2 on 2023-04-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai', '0008_alter_story_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='story_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='title_translation',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
