# Generated by Django 4.2 on 2023-04-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai', '0009_story_story_text_story_title_translation'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('native_language', models.CharField(max_length=50)),
                ('target_language', models.CharField(max_length=50)),
                ('characters', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('theme', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
