# Generated by Django 4.2 on 2023-04-30 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai', '0010_storyparams'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyparams',
            name='selected_level',
            field=models.CharField(default='a1', max_length=2),
        ),
    ]
