# Generated by Django 4.2 on 2023-04-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai', '0011_storyparams_selected_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyparams',
            name='generate_image',
            field=models.BooleanField(default=False),
        ),
    ]
