# Generated by Django 4.2 on 2023-05-13 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openai', '0013_storyparams_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('dep', models.CharField(max_length=255)),
                ('head', models.CharField(max_length=255)),
                ('lemma', models.CharField(max_length=255)),
                ('pos', models.CharField(max_length=255)),
                ('tag', models.CharField(max_length=255)),
                ('is_alpha', models.BooleanField()),
                ('is_stop', models.BooleanField()),
                ('is_punct', models.BooleanField()),
                ('is_space', models.BooleanField()),
                ('is_digit', models.BooleanField()),
                ('is_currency', models.BooleanField()),
                ('is_quote', models.BooleanField()),
                ('is_bracket', models.BooleanField()),
                ('is_left_punct', models.BooleanField()),
                ('is_right_punct', models.BooleanField()),
                ('is_title', models.BooleanField()),
                ('is_upper', models.BooleanField()),
                ('is_lower', models.BooleanField()),
                ('is_oov', models.BooleanField()),
                ('is_sent_start', models.BooleanField()),
                ('is_sent_end', models.BooleanField()),
                ('index', models.IntegerField()),
                ('idx', models.IntegerField()),
                ('text_with_ws', models.CharField(max_length=255)),
                ('sentiment', models.FloatField()),
                ('ent_type', models.CharField(max_length=255)),
                ('ent_iob', models.CharField(max_length=255)),
                ('ent_kb_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('childeren', models.JSONField()),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openai.sentence')),
            ],
        ),
    ]
