# Generated by Django 4.2 on 2023-05-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openai', '0014_word'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='childeren',
            new_name='children',
        ),
    ]
