# Generated by Django 4.2 on 2023-05-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openai', '0014_word_sentence_words'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='parent',
        ),
        migrations.AddField(
            model_name='word',
            name='parent',
            field=models.ManyToManyField(blank=True, null=True, related_name='parent_word', to='openai.word'),
        ),
    ]
