# Generated by Django 4.2 on 2023-05-11 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openai', '0015_remove_word_parent_word_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='words',
        ),
        migrations.AddField(
            model_name='word',
            name='sentence',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='openai.sentence'),
            preserve_default=False,
        ),
    ]
