# Generated by Django 4.2 on 2023-05-17 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openai', '0017_savedword_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedword',
            name='translation_sentence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='translation_sentence', to='openai.sentence'),
            preserve_default=False,
        ),
    ]
