# Generated by Django 4.2 on 2023-04-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('neural', 'Neural'), ('standard', 'Standard')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('language_code', models.CharField(max_length=10)),
                ('language_name', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
