# Generated by Django 4.2 on 2023-04-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voice',
            name='supported_engines',
            field=models.ManyToManyField(to='s3.engine'),
        ),
    ]
