# Generated by Django 4.2 on 2023-04-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
